// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/profile/data/repo/update_profile_data_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i4;
import 'package:online_exam_app/features/profile/data/datasources/local/update_profile_data_local_data_source_contract.dart'
    as _i8;
import 'package:online_exam_app/features/profile/data/datasources/remote/update_profile_data_remote_data_source_contract.dart'
    as _i2;
import 'package:online_exam_app/features/profile/data/models/update-request.dart'
    as _i6;
import 'package:online_exam_app/features/profile/data/models/update_user_dto.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UpdateProfileDataRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileDataRemoteDataSourceContract extends _i1.Mock
    implements _i2.UpdateProfileDataRemoteDataSourceContract {
  MockUpdateProfileDataRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.UpdateUserDto>> updateProfileData(
    _i6.UpdateRequest? updateRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileData, [updateRequest]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.UpdateUserDto>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.UpdateUserDto>>(
                this,
                Invocation.method(#updateProfileData, [updateRequest]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.UpdateUserDto>>);
}

/// A class which mocks [UpdateProfileDataLocalDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateProfileDataLocalDataSourceContract extends _i1.Mock
    implements _i8.UpdateProfileDataLocalDataSourceContract {
  MockUpdateProfileDataLocalDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.UpdateUserDto>> updateProfileData(
    String? token,
    _i6.UpdateRequest? updateRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfileData, [token, updateRequest]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.UpdateUserDto>>.value(
              _i7.dummyValue<_i4.BaseResponse<_i5.UpdateUserDto>>(
                this,
                Invocation.method(#updateProfileData, [token, updateRequest]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.UpdateUserDto>>);
}
