// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/sign_up/data/repo/signup_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:online_exam_app/api/api_client.dart' as _i3;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i8;
import 'package:online_exam_app/features/sign_up/data/datasources/local/signup_local_datasource_impl.dart'
    as _i4;
import 'package:online_exam_app/features/sign_up/data/datasources/remote/signup_remote_datasource_impl.dart'
    as _i7;
import 'package:online_exam_app/features/sign_up/data/models/user_dto.dart'
    as _i2;
import 'package:online_exam_app/features/sign_up/data/models/user_request.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserDto_0 extends _i1.SmartFake implements _i2.UserDto {
  _FakeUserDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeApiClient_1 extends _i1.SmartFake implements _i3.ApiClient {
  _FakeApiClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignUpLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpLocalDataSourceImpl extends _i1.Mock
    implements _i4.SignUpLocalDataSourceImpl {
  MockSignUpLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.UserDto> signUp(_i6.UserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i5.Future<_i2.UserDto>.value(
              _FakeUserDto_0(this, Invocation.method(#signUp, [request])),
            ),
          )
          as _i5.Future<_i2.UserDto>);
}

/// A class which mocks [SignupRemoteDatasourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignupRemoteDatasourceImpl extends _i1.Mock
    implements _i7.SignupRemoteDatasourceImpl {
  MockSignupRemoteDatasourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.ApiClient get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeApiClient_1(this, Invocation.getter(#api)),
          )
          as _i3.ApiClient);

  @override
  set api(_i3.ApiClient? _api) => super.noSuchMethod(
    Invocation.setter(#api, _api),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i8.BaseResponse<_i2.UserDto>> signUp(_i6.UserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [request]),
            returnValue: _i5.Future<_i8.BaseResponse<_i2.UserDto>>.value(
              _i9.dummyValue<_i8.BaseResponse<_i2.UserDto>>(
                this,
                Invocation.method(#signUp, [request]),
              ),
            ),
          )
          as _i5.Future<_i8.BaseResponse<_i2.UserDto>>);
}
