// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/hom_screen/data/datasources/remote/get_all_subjects_remote_ds_impl._test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:online_exam_app/api/api_client.dart' as _i6;
import 'package:online_exam_app/features/forget_password/data/models_dto/forget_password_request.dart'
    as _i10;
import 'package:online_exam_app/features/forget_password/data/models_dto/forget_password_response_dto.dart'
    as _i4;
import 'package:online_exam_app/features/hom_screen/data/models/subject_response.dart'
    as _i5;
import 'package:online_exam_app/features/login/data/models_dto/login/request_login.dart'
    as _i8;
import 'package:online_exam_app/features/login/data/models_dto/login/response_login_dto.dart'
    as _i2;
import 'package:online_exam_app/features/sign_up/data/models/signup_response.dart'
    as _i3;
import 'package:online_exam_app/features/sign_up/data/models/user_request.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponseLoginDto_0 extends _i1.SmartFake
    implements _i2.ResponseLoginDto {
  _FakeResponseLoginDto_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignupResponse_1 extends _i1.SmartFake
    implements _i3.SignupResponse {
  _FakeSignupResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeForgetPasswordResponseDto_2 extends _i1.SmartFake
    implements _i4.ForgetPasswordResponseDto {
  _FakeForgetPasswordResponseDto_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSubjectResponse_3 extends _i1.SmartFake
    implements _i5.SubjectResponse {
  _FakeSubjectResponse_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i6.ApiClient {
  MockApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.ResponseLoginDto> login(_i8.RequestLogin? requestLogin) =>
      (super.noSuchMethod(
            Invocation.method(#login, [requestLogin]),
            returnValue: _i7.Future<_i2.ResponseLoginDto>.value(
              _FakeResponseLoginDto_0(
                this,
                Invocation.method(#login, [requestLogin]),
              ),
            ),
          )
          as _i7.Future<_i2.ResponseLoginDto>);

  @override
  _i7.Future<_i3.SignupResponse> signUp(_i9.UserRequest? userRequest) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [userRequest]),
            returnValue: _i7.Future<_i3.SignupResponse>.value(
              _FakeSignupResponse_1(
                this,
                Invocation.method(#signUp, [userRequest]),
              ),
            ),
          )
          as _i7.Future<_i3.SignupResponse>);

  @override
  _i7.Future<_i4.ForgetPasswordResponseDto> forgetPassword(
    _i10.ForgetPasswordRequest? forgetPasswordRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#forgetPassword, [forgetPasswordRequest]),
            returnValue: _i7.Future<_i4.ForgetPasswordResponseDto>.value(
              _FakeForgetPasswordResponseDto_2(
                this,
                Invocation.method(#forgetPassword, [forgetPasswordRequest]),
              ),
            ),
          )
          as _i7.Future<_i4.ForgetPasswordResponseDto>);

  @override
  _i7.Future<_i5.SubjectResponse> getAllSubjects(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, [token]),
            returnValue: _i7.Future<_i5.SubjectResponse>.value(
              _FakeSubjectResponse_3(
                this,
                Invocation.method(#getAllSubjects, [token]),
              ),
            ),
          )
          as _i7.Future<_i5.SubjectResponse>);
}
