// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/profile/presentation/view_model/profile_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i6;
import 'package:online_exam_app/features/profile/data/models/update-request.dart'
    as _i11;
import 'package:online_exam_app/features/profile/domain/models/update_user_model.dart'
    as _i10;
import 'package:online_exam_app/features/profile/domain/models/user_model.dart'
    as _i7;
import 'package:online_exam_app/features/profile/domain/repo/get_profile_data_repo_contract.dart'
    as _i2;
import 'package:online_exam_app/features/profile/domain/repo/update_profile_data_repo_contract.dart'
    as _i3;
import 'package:online_exam_app/features/profile/domain/use_cases/get_user_data_use_case.dart'
    as _i4;
import 'package:online_exam_app/features/profile/domain/use_cases/update_user_data_use_case.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetProfileDataRepoContract_0 extends _i1.SmartFake
    implements _i2.GetProfileDataRepoContract {
  _FakeGetProfileDataRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateProfileDataRepoContract_1 extends _i1.SmartFake
    implements _i3.UpdateProfileDataRepoContract {
  _FakeUpdateProfileDataRepoContract_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(parent, parentInvocation);
}

/// A class which mocks [GetUserDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetUserDataUseCase extends _i1.Mock
    implements _i4.GetUserDataUseCase {
  MockGetUserDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetProfileDataRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeGetProfileDataRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.GetProfileDataRepoContract);

  @override
  set repo(_i2.GetProfileDataRepoContract? _repo) => super.noSuchMethod(
    Invocation.setter(#repo, _repo),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i6.BaseResponse<_i7.UserModel>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i5.Future<_i6.BaseResponse<_i7.UserModel>>.value(
              _i8.dummyValue<_i6.BaseResponse<_i7.UserModel>>(
                this,
                Invocation.method(#call, []),
              ),
            ),
          )
          as _i5.Future<_i6.BaseResponse<_i7.UserModel>>);
}

/// A class which mocks [UpdateUserDataUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockUpdateUserDataUseCase extends _i1.Mock
    implements _i9.UpdateUserDataUseCase {
  MockUpdateUserDataUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.UpdateProfileDataRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeUpdateProfileDataRepoContract_1(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i3.UpdateProfileDataRepoContract);

  @override
  set repo(_i3.UpdateProfileDataRepoContract? _repo) => super.noSuchMethod(
    Invocation.setter(#repo, _repo),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i6.BaseResponse<_i10.UpdateUserModel>> call(
    _i11.UpdateRequest? updateRequest,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [updateRequest]),
            returnValue:
                _i5.Future<_i6.BaseResponse<_i10.UpdateUserModel>>.value(
                  _i8.dummyValue<_i6.BaseResponse<_i10.UpdateUserModel>>(
                    this,
                    Invocation.method(#call, [updateRequest]),
                  ),
                ),
          )
          as _i5.Future<_i6.BaseResponse<_i10.UpdateUserModel>>);
}
