// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/hom_screen/presentation/view_model/subject_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i5;
import 'package:online_exam_app/features/hom_screen/domain/models/subjectModel.dart'
    as _i6;
import 'package:online_exam_app/features/hom_screen/domain/repo/get_all_subjects_repo_contrct.dart'
    as _i2;
import 'package:online_exam_app/features/hom_screen/domain/usecases/get_all_subjects_use_cases.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAllSubjectsRepoContract_0 extends _i1.SmartFake
    implements _i2.GetAllSubjectsRepoContract {
  _FakeGetAllSubjectsRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllSubjectsUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllSubjectsUseCases extends _i1.Mock
    implements _i3.GetAllSubjectsUseCases {
  MockGetAllSubjectsUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetAllSubjectsRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeGetAllSubjectsRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.GetAllSubjectsRepoContract);

  @override
  set repo(_i2.GetAllSubjectsRepoContract? _repo) => super.noSuchMethod(
    Invocation.setter(#repo, _repo),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.BaseResponse<List<_i6.SubjectModel>>> call(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#call, [token]),
            returnValue:
                _i4.Future<_i5.BaseResponse<List<_i6.SubjectModel>>>.value(
                  _i7.dummyValue<_i5.BaseResponse<List<_i6.SubjectModel>>>(
                    this,
                    Invocation.method(#call, [token]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<List<_i6.SubjectModel>>>);
}
