// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/profile/domain/usecases/get_user_data_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i4;
import 'package:online_exam_app/features/profile/domain/models/user_model.dart'
    as _i5;
import 'package:online_exam_app/features/profile/domain/repo/get_profile_data_repo_contract.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetProfileDataRepoContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetProfileDataRepoContract extends _i1.Mock
    implements _i2.GetProfileDataRepoContract {
  MockGetProfileDataRepoContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.BaseResponse<_i5.UserModel>> getProfileData(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, [token]),
            returnValue: _i3.Future<_i4.BaseResponse<_i5.UserModel>>.value(
              _i6.dummyValue<_i4.BaseResponse<_i5.UserModel>>(
                this,
                Invocation.method(#getProfileData, [token]),
              ),
            ),
          )
          as _i3.Future<_i4.BaseResponse<_i5.UserModel>>);
}
