// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/sign_up/presentation/view_model/signup_viewmodel_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i5;
import 'package:online_exam_app/features/sign_up/data/models/user_request.dart'
    as _i7;
import 'package:online_exam_app/features/sign_up/domain/models/user_model.dart'
    as _i6;
import 'package:online_exam_app/features/sign_up/domain/repo/signup_repo_contract.dart'
    as _i2;
import 'package:online_exam_app/features/sign_up/domain/usecases/signup_usecase.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSignUpRepoContract_0 extends _i1.SmartFake
    implements _i2.SignUpRepoContract {
  _FakeSignUpRepoContract_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SignUpUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignUpUseCase extends _i1.Mock implements _i3.SignUpUseCase {
  MockSignUpUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SignUpRepoContract get repo =>
      (super.noSuchMethod(
            Invocation.getter(#repo),
            returnValue: _FakeSignUpRepoContract_0(
              this,
              Invocation.getter(#repo),
            ),
          )
          as _i2.SignUpRepoContract);

  @override
  _i4.Future<_i5.BaseResponse<_i6.UserModel>> call(_i7.UserRequest? request) =>
      (super.noSuchMethod(
            Invocation.method(#call, [request]),
            returnValue: _i4.Future<_i5.BaseResponse<_i6.UserModel>>.value(
              _i8.dummyValue<_i5.BaseResponse<_i6.UserModel>>(
                this,
                Invocation.method(#call, [request]),
              ),
            ),
          )
          as _i4.Future<_i5.BaseResponse<_i6.UserModel>>);
}
