// Mocks generated by Mockito 5.4.6 from annotations
// in online_exam_app/test/features/hom_screen/data/repo/get_all_subjects_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:online_exam_app/api/api_client.dart' as _i2;
import 'package:online_exam_app/config/base_response/base_response.dart' as _i5;
import 'package:online_exam_app/features/hom_screen/data/datasources/local/get_all_subjects_local_ds_impl.dart'
    as _i3;
import 'package:online_exam_app/features/hom_screen/data/datasources/remote/get_all_subjects_remote_ds_impl..dart'
    as _i8;
import 'package:online_exam_app/features/hom_screen/data/models/subject_Dto.dart'
    as _i9;
import 'package:online_exam_app/features/hom_screen/domain/models/subjectModel.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllSubjectsLocalDsImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllSubjectsLocalDsImpl extends _i1.Mock
    implements _i3.GetAllSubjectsLocalDsImpl {
  MockGetAllSubjectsLocalDsImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.BaseResponse<List<_i6.SubjectModel>>> getAllSubjects(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, [token]),
            returnValue:
                _i4.Future<_i5.BaseResponse<List<_i6.SubjectModel>>>.value(
                  _i7.dummyValue<_i5.BaseResponse<List<_i6.SubjectModel>>>(
                    this,
                    Invocation.method(#getAllSubjects, [token]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<List<_i6.SubjectModel>>>);
}

/// A class which mocks [GetAllSubjectsRemoteDsImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllSubjectsRemoteDsImpl extends _i1.Mock
    implements _i8.GetAllSubjectsRemoteDsImpl {
  MockGetAllSubjectsRemoteDsImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ApiClient get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#api)),
          )
          as _i2.ApiClient);

  @override
  set api(_i2.ApiClient? _api) => super.noSuchMethod(
    Invocation.setter(#api, _api),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<_i5.BaseResponse<List<_i9.SubjectsDto>>> getAllSubjects(
    String? token,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getAllSubjects, [token]),
            returnValue:
                _i4.Future<_i5.BaseResponse<List<_i9.SubjectsDto>>>.value(
                  _i7.dummyValue<_i5.BaseResponse<List<_i9.SubjectsDto>>>(
                    this,
                    Invocation.method(#getAllSubjects, [token]),
                  ),
                ),
          )
          as _i4.Future<_i5.BaseResponse<List<_i9.SubjectsDto>>>);
}
